server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/liuyilei/microservicecloud-config #GitHub上面的git仓库名字

